### ISSUE TITLE
dev.codefor.de links on lab pages

### ISSUE THREAD

**Issue by jochenklar** [okfde/codefor.de#303] opened 2021-11-21 11:21 UTC
Hi, if I go to https://codefor.de/labs/berlin/ instead of https://codefor.de/berlin/ the project links go to dev.codefor.de which does not exist anymore. I guess it has something to do with nginx rewrite magic.

**Comment by fnogatz** [comment] 2022-07-27 21:50
Hm, I think the root cause is that https://codefor.de/labs/berlin/ probably should not exist or it should redirect to https://codefor.de/berlin instead. Labs that were founded only recently can't be accessed using the `codefor.de/labs/...` prefix, take for instance Kaiserslautern: https://codefor.de/labs/kaiserslautern/

**Comment by sonjafischbauer** [comment] 2023-04-24 13:10
I just tried https://codefor.de/labs/berlin/ and it redirects me to home. 

Could we consider this issue fixed and close it?

**Closed** 2023-09-04 13:11 UTC
Labels: deployment
